#!/usr/bin/env bash

# Get fastest mirrors
echo 'Getting fastest mirrors'
sudo reflector --verbose --country 'United States' -l 20 -p https --sort rate --save /etc/pacman.d/mirrorlist

# Setup pacman with parallel downloads and color
echo 'Enabling parallel downloads and colors'
sudo sed -i '/Color/s/^#//' /etc/pacman.conf
sudo sed -i '/Color/a ILoveCandy' /etc/pacman.conf
sudo sed -i "/\[multilib\]/,/Include/"'s/^#//' /etc/pacman.conf
sudo sed -i 's/#ParallelDownloads = 5/ParallelDownloads = 25/g' /etc/pacman.conf

# Setup Yay
echo 'Setting up yay'
sudo pacman -S --needed git base-devel && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si

# Go back and delete the created yay directory
echo 'Remove yay folder'
cd ..
rm -rf yay

# Update packages
echo 'Updating packages'
yay -Syyu

# Install packages from pkglist
echo 'Installing requested packages'
yay -S acpilight blueman bluez bluez-utils swappy firefox foot git gnome-keyring arc-gtk-theme go grim wireplumber linux linux-headers make mako neofetch nvidia-dkms pamixer pavucontrol polkit-gnome qt5-wayland qt6-wayland qt5ct reflector sddm slurp swayidle swaylock ttc-iosevka ttf-nerd-fonts-symbols-2048-em vim wl-clipboard wofi xdg-user-dirs feh playerctl wget steam rust rust-analyzer cpupower nodejs npm power-profiles-daemon noto-fonts-cjk xplr gammastep helix

echo 'Installing AUR packages'
yay -S candy-icons-git
yay -S hyprland-git
yay -S hyprpicker-git
yay -S nvidia-vaapi-driver-git
yay -S xdg-desktop-portal-hyprland-git
yay -S sddm-sugar-candy-git
yay -S visual-studio-code-bin
yay -S waybar-hyprland-git
yay -S wlogout
yay -S beautyline
yay -S bibata-cursor-theme
yay -S hyprpaper-git

# Create file for nvidia used by hyprland
echo 'Setup nvidia.conf'
sudo touch /etc/modprobe.d/nvidia.conf
echo 'options nvidia-drm modeset=1' | sudo tee /etc/modprobe.d/nvidia.conf

# Enables services
echo 'Enabling services'
sudo systemctl enable power-profiles-daemon.service
sudo systemctl enable sddm.service
sudo systemctl enable bluetooth.service

# Add user to groups
echo 'Add user to wheel and video groups'
sudo usermod -aG wheel $(whoami)
sudo usermod -aG video $(whoami)

# Copy config files
echo 'Copying config files'
cp -r ./foot ~/.config
cp -r ./hypr ~/.config
cp -r ./mako ~/.config
cp -r ./waybar ~/.config
cp -r ./wlogout ~/.config
cp -r ./wofi ~/.config

# Copy bash config
echo 'Copy bash config'
cp ./.bashrc ~/

# Create hyprland desktop entry
echo 'Create custom hyprland desktop entry'
sudo cp ./hyprland.desktop /usr/share/wayland-sessions/

# Copy sddm config file
echo 'Copy sddm config file'
sudo cp ./sddm.conf /etc

# Update mkinitcpio with nvidia config
echo "Updating mkinitcpio config with nvidia"
echo "
MODULES=(btrfs nvidia nvidia_modeset nvidia_uvm nvidia_drm)
BINARIES=(/usr/bin/btrfs)
FILES=()
HOOKS=(base udev autodetect keyboard keymap modconf block filesystems fsck)" | sudo tee /etc/mkinitcpio.conf

# Add nvidia to systemd-boot 
echo 'Setup nvidia systemd-boot'
sudo sed -i "s/rootfstype=btrfs/& cow_spacesize=10G copytoram=n nvidia nvidia-drm.modeset=1 nouveau.modeset=0 i915.modeset=1 radeon.modeset=1 nvme_load=yes module_blacklist=pcspk/" /boot/loader/entries/*.conf
