#!/bin/bash

THEME='Adwaita-dark'
ICONS='candy-icons'
FONT='JetBrainsMono Nerd Font 14'
CURSOR='Adwaita'

SCHEMA='gsettings set org.gnome.desktop.interface'

apply_themes() {
	${SCHEMA} gtk-theme "$THEME"
	${SCHEMA} icon-theme "$ICONS"
	${SCHEMA} cursor-theme "$CURSOR"
	${SCHEMA} font-name "$FONT"
	${SCHEMA} color-scheme prefer-dark
}

apply_themes