#!/bin/bash

## Set GTK Themes, Icons, Cursor and Fonts

THEME='Dracula'
ICONS='candy-icons'
FONT='JetBrainsMono Nerd Font 14'
CURSOR='Dracula'

SCHEMA='gsettings set org.gnome.desktop.interface'

apply_themes() {
	${SCHEMA} gtk-theme "$THEME"
	${SCHEMA} icon-theme "$ICONS"
	${SCHEMA} cursor-theme "$CURSOR"
	${SCHEMA} font-name "$FONT"
}

apply_themes