#!/bin/bash

THEME='Adwaita-dark'
ICONS='candy-icons'
FONT='JetBrainsMono Nerd Font 14'
CURSOR='Adwaita-dark'
COLOR_SCHEME='prefer-dark'

SCHEMA='gsettings set org.gnome.desktop.interface'

apply_themes() {
	${SCHEMA} gtk-theme "$THEME"
	${SCHEMA} icon-theme "$ICONS"
	${SCHEMA} cursor-theme "$CURSOR"
	${SCHEMA} font-name "$FONT"
	${SCHEMA} color-scheme "$COLOR_SCHEME"
}

apply_themes