require '_plugins'
require '_colorscheme'
require '_keymaps'
require '_impatient'
require '_options'
require '_telescope'
require '_nvim-tree'
require '_lualine'
require '_treesitter'
require '_cmp'
require '_autopairs'
require '_comment'
require '_gitsigns'
require '_toggleterm'
require '_lsp'

